#ifndef APP_CLIENTS_TUI_CHAT_OPTION_H
#define APP_CLIENTS_TUI_CHAT_OPTION_H

typedef enum ChatOption {
    CHAT_OPTION_MUTE_8H = 0,
    CHAT_OPTION_MUTE_WEEK,
    CHAT_OPTION_MUTE_ALWAYS,
    CHAT_OPTION_UNMUTE,
    CHAT_OPTION_PIN,
    CHAT_OPTION_UNPIN,
    CHAT_OPTION_ARCHIVE,
    CHAT_OPTION_UNARCHIVE,
    CHAT_OPTION_THEME,
    CHAT_OPTION_TONE_CHOOSE,
    CHAT_OPTION_TONE_NONE,
    CHAT_OPTION_TONE_DEFAULT,
    CHAT_OPTION_CLEAR_DRAFT,
    CHAT_OPTION_SOFT_LOCK,
    CHAT_OPTION_SOFT_UNLOCK,
    CHAT_OPTION_DELETE_CHAT,
    CHAT_OPTION_INFO,
    CHAT_OPTION_COUNT
} ChatOption;

const char *chat_option_label(ChatOption option);

#endif
